import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterContext from '@/context/ToasterContext'
import AuthContext from '@/context/AuthContext'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat-App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AuthContext>
          <ModalProvider />
          <ToasterContext />
          <SocketProvider>
            {children}
          </SocketProvider>
        </AuthContext>
      </body>
    </html>
  )
}
